config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resources :banner_boxes do
      collection do
        post :update_positions
      end
      member do
        get :clone
      end
    end
    resource :banner_box_settings
  end
end

app/models/spree/banner_box.rb
module Spree
  class BannerBox < ActiveRecord::Base
    # has_attached_file :attachment,
    #                     :path => ":rails_root/public/spree/banners/:id/:style_:basename.:extension",
    #                     :styles => { :mini => "80x80#", :small => "120x120#" },
    #                     :s3_credentials => "#{Rails.root}/config/aws.yml",
    #                     :convert_options => { :all => '-strip -auto-orient' }

        has_attached_file :attachment,
                      s3_credentials: {
                        access_key_id:  ENV['S3_ACCESS_KEY'],
                        secret_access_key: ENV['S3_SECRET'],
                        bucket: ENV['S3_BUCKET']
                      },
                      storage: :s3,
                      s3_headers: { "Cache-Control" => 1.year.from_now.httpdate },
                      s3_protocol:  "https",
                      s3_region: ENV['S3_REGION'],
                      bucket: ENV['S3_BUCKET'],
                      # styles: { mini:'192x64#', default:'1000x135>', logo:'250x71#', minibanner:'269x196#', banner_marca: '327x260#', banners_slider_home:'1362x440#', banners_home:'327x260#', banners_marcas:'1000x100#', banner_cupom:'1000x60#', banner_cupom_mobile:'260x57#' },
                      default_style: :default,
                      url: ":s3_alias_url",
                      path: "/banners/:id/:style/:basename.:extension",
                      default_url:  "/banners/:id/:style/:basename.:extension",
                      s3_host_alias: Proc.new {|attachment| "cdn#{attachment.instance.id % 4}.retroca.com.br" }
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    validates_presence_of :category
    validates_attachment_presence :attachment
    validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg', 'image/x-png', 'image/pjpeg'], :message => I18n.t(:images_only)

    # scope :enable, lambda { |category| {:conditions => {:enabled => true, :category => category}} }
    scope :enable, -> (category) { where(:enabled => true, :category => category) }

    # Load user defined paperclip settings
    Spree::BannerBox.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:banner_styles]).symbolize_keys!
    # Spree::BannerBox.attachment_definitions[:attachment][:path] = Spree::Config[:banner_path]
    # Spree::BannerBox.attachment_definitions[:attachment][:url] = Spree::Config[:banner_url]
    # Spree::BannerBox.attachment_definitions[:attachment][:default_url] = Spree::Config[:banner_default_url]
    # Spree::BannerBox.attachment_definitions[:attachment][:default_style] = Spree::Config[:banner_default_style]

    def initialize(*args)
      super(*args)
      last_banner = BannerBox.last
      self.position = last_banner ? last_banner.position + 1 : 0
    end

    # for adding banner_boxes which are closely related to existing ones
    # define "duplicate_extra" for site-specific actions, eg for additional fields
    def duplicate
      p = self.dup
      p.category = 'COPY OF ' + category
      p.created_at = p.updated_at = nil
      p.url = url
      p.attachment = attachment

      # allow site to do some customization
      p.send(:duplicate_extra, self) if p.respond_to?(:duplicate_extra)
      p.save!
      p
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width = geometry.width
      self.attachment_height = geometry.height
    end

    def set_list_position(i)
      update_column(:position, i)
    end
  end
end

app/controllers/spree/admin/banner_boxes_controller.rb
module Spree
  module Admin
    class BannerBoxesController < ResourceController

      def index
        respond_with(@collection)
      end

      def show
        redirect_to( :action => :edit )
      end

      def clone
        @new = @banner_box.duplicate

        if @new.save
          flash.notice = I18n.t('notice_messages.banner_box_cloned')
        else
          flash.notice = I18n.t('notice_messages.banner_box_not_cloned')
        end

        respond_with(@new) { |format| format.html { redirect_to edit_admin_banner_box_url(@new) } }
      end

      protected
      def find_resource
        Spree::BannerBox.find(params[:id])
      end

      def location_after_save
        edit_admin_banner_box_url(@banner_box)
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:s] ||= "created_at desc"
        params[:page] ||= 1
        # params[:category] ||= "compra"
        # params[:q][:enabled_eq] = params[:enabled] if params[:enabled]

        # params[:q][:category_in] = case params[:category]
        #   when 'compra' then %w[mainbanner minibanner1 minibanner2]
        #   when 'narrow' then %w[narrowbanner cupombanner cupombannermobile]
        #   when 'landing' then %w[radio_landing apae_landing]
        #   when 'marcas' then %w[brandbanner]
        #   when 'logos' then %w[homelogo2]
        #   when 'lateral' then %w[sidebanner]
        #   else %w[params[:category]]
        # end

        @search = super.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(15)
      end
    end
  end
end

app/helpers/spree/banner_boxes_helper.rb
# coding: utf-8
module Spree
  module BannerBoxesHelper
    
    def banner_image_tag(banner, ga_event, params={})
      link_to(image_tag(banner.attachment.url(params[:style].to_sym), alt: banner.presentation), (banner.url.blank? ? "javascript:void(0)" : banner.url), target: (banner.target_blank? ? "_blank" : ""), onClick: ga_event)
    end
        
    def insert_slider_box(params={})
      params[:category] ||= "home"
      params[:ul_class] ||= "bxslider-home"
      params[:li_class] ||= "clearfix"
      params[:div_class] ||= "slide-image"
      params[:style] ||= Spree::Config[:banner_default_style]
      @@banner = Spree::BannerBox.enable(params[:category])
      if @@banner.blank?
        return ''
      end
      res = []
      banner = @@banner.sort_by { |ban| ban.position }
                
      content_tag :ul, class: params[:ul_class] do
        banner.map do |ban| 
          content_tag :li, class: params[:li_class] do 
            content_tag :div, class: params[:div_class] do 
              link_to(image_tag(ban.attachment.url(params[:style].to_sym), alt: ban.presentation), (ban.url.blank? ? "javascript: void(0)" : ban.url), target: (ban.target_blank? ? "_blank" : ""))
            end
          end
        end.join().html_safe  
      end    
    end
    
    def insert_slider_box3(params={})
      params[:category] ||= "home"
      params[:ul_class] ||= "bxslider-home"
      params[:li_class] ||= "clearfix"
      params[:style] ||= Spree::Config[:banner_default_style]

      @@banner = Spree::BannerBox.enable(params[:category])

      return '' if @@banner.blank?

      ga_event = "ga('send', 'event', { eventCategory: 'internal-promotion', eventAction: 'clicked', eventLabel: 'GA_EVENTO'});" unless params[:ga_event].blank?

      banner = @@banner.sort_by { |ban| ban.position }
            
      content_tag :div, class: params[:ul_class] do 
        banner.each_with_index.map do |ban, i|
          ga_string = ""
          ga_string = ga_event.gsub("GA_EVENTO", "#{params[:ga_event]}-#{i+1}") unless params[:ga_event].blank?

          content_tag :div, class: params[:li_class] do
            link_to(image_tag(ban.attachment.url(params[:style].to_sym), alt: ban.presentation), (ban.url.blank? ? "javascript: void(0)" : ban.url), target: (ban.target_blank? ? "_blank" : ""), onClick: ga_string.html_safe)
          end
        end.join().html_safe
      end  
    end
      
    def insert_banner_box(params={})
      params[:category] ||= "home"
      params[:class] ||= "banner"
      params[:style] ||= Spree::Config[:banner_default_style]
      params[:list] ||= false
      @@banner = Spree::BannerBox.enable(params[:category])
              
      if @@banner.blank?
        return ''
      end
                
      res = []
      banner = @@banner.sort_by { |ban| ban.position }
              
      onClick_ga_event = "ga('send', 'event', { eventCategory: 'internal-promotion', eventAction: 'clicked', eventLabel: '#{params[:category]}'});"
                 
      if (params[:list])
        content_tag(:ul, banner.map{|ban| content_tag(:li, banner_image_tag(ban,onClick_ga_event,params), :class => params[:class])}.join().html_safe )
      else
        banner.map{|ban| content_tag(:div, banner_image_tag(ban,onClick_ga_event,params), :class => params[:class])}.join().html_safe
      end
    end
    
    def insert_banner_box3(params={})
      params[:category] ||= "home"
      params[:class] ||= "banner"
      params[:style] ||= Spree::Config[:banner_default_style]
      params[:list] ||= false
      
      @@banner = Spree::BannerBox.enable(params[:category])

      return '' if @@banner.blank?

      banner = @@banner.sort_by { |ban| ban.position }

      ga_event = "ga('send', 'event', { eventCategory: 'internal-promotion', eventAction: 'clicked', eventLabel: 'GA_EVENTO'});" unless params[:ga_event].blank?

      if (params[:list])
        content_tag :ul, :class => params[:class] do
          banner.each_with_index.map{ |ban, i|
            ga_string = ""
            ga_string = ga_event.gsub("GA_EVENTO", "#{params[:ga_event]}-#{i+1}") unless params[:ga_event].blank?
            content_tag(:li, banner_image_tag(ban, ga_string.html_safe, params))
          }.join().html_safe
        end
      else
        banner.each_with_index.map{ |ban, i| content_tag(:li, banner_image_tag(ban, "ga('send', 'event', { eventCategory: 'internal-promotion', eventAction: 'clicked', eventLabel: 'carousel-#{i+1}'});".html_safe, params), :class => params[:class])}.join().html_safe
      end
    end
    
    def insert_marcas_banner_pannel(params={})
      params[:category] ||= 'brandbanner'
      params[:class] ||= 'banner_pannel'
      params[:style] ||= Spree::Config[:banner_default_style]
      params[:btn_class] ||= "button"
      # params[:list] ||= false
      @@banner = Spree::BannerBox.enable(params[:category])
              
      if @@banner.blank?
        return ''
      end
              
      res = []
      banner = @@banner.sort_by { |ban| ban.position }
           
      ga_event = "ga('send', 'event', { eventCategory: 'internal-promotion', eventAction: 'clicked', eventLabel: '#{params[:category]}'});"
           
      banners_content = banner.map do |ban|
        banner_image = banner_image_tag(ban, ga_event, params)
        txt = ban.presentation.split("-")
        pannel_desc = []
             
        unless ban.url.blank?
          pannel_desc << content_tag(:div, link_to("Comprar", ban.url, class: params[:btn_class], target:(ban.target_blank? ? "_blank" : ""), onClick: ga_event), :class => "button-container")
        end
              
        pannel_desc = []
        pannel_desc << content_tag(:h4, txt[0])
        description = txt.size > 1 ? txt[1] : "#{txt[0]} com até 60% de desconto no Retroca!"
        pannel_desc << content_tag(:p, description)
                    
        content_tag(:div, banner_image + pannel_desc.join().html_safe, :class => params[:class])
             
      end.join().html_safe
        
      content_tag :div, banners_content, :class => 'banner-pannel-container'
    end
              
    def insert_marcas_banner_pannel3(params={})
      params[:category] ||= 'brandbanner'
      params[:class] ||= 'banner_pannel'
      params[:style] ||= Spree::Config[:banner_default_style]
      params[:btn_class] ||= "button"
      # params[:list] ||= false
      @@banner = Spree::BannerBox.enable(params[:category])
              
      if @@banner.blank?
        return ''
      end
              
      res = []
      banner = @@banner.sort_by { |ban| ban.position }
           
      ga_event = "ga('send', 'event', { eventCategory: 'internal-promotion', eventAction: 'clicked', eventLabel: '#{params[:category]}'});"
           
      banners_content = banner.map do |ban|
        content_tag :li do
          link_to (ban.url.blank? ? "javascript:void(0)" : ban.url), target: (ban.target_blank? ? "_blank" : ""), onClick: ga_event do
            content_tag :div, :class => 'bloco-marcas' do
              # image
              img = content_tag :div, :class => 'cut_img' do
                image_tag(ban.attachment.url(params[:style].to_sym), alt: ban.presentation)
              end
              
              # description
              description = content_tag :p, ban.presentation
              
              img + description
            end
          end
        end
      end.join().html_safe
              
      content_tag :ul, banners_content
    end
  end
end

app/views/spree/admin/banner_boxes/_form.html.erb
<div data-hook="admin_page_form_fields" class="row">

	<div class="col-md-6 col-sm-6" data-hook="admin_page_form_left">

		<div class="form-group">
			<%= f.label :category, raw(t(:category) + content_tag(:span, ' *', :class => 'required')) %>
			<%= f.text_field :category, :class => 'form-control' %>
			<%= f.error_message_on :category %>
		</div>
	
		<div class="form-group">
			<%= f.label :url, raw(t(:url)) %>
			<%= f.text_field :url, :class => 'form-control' %>
			<%= f.error_message_on :url %>
		</div>
	</div>
	
	<div class="col-md-6 col-sm-6" data-hook="admin_page_form_right">
		
		<div class="form-group">
	    	<%= f.label :presentation, t(:presentation) %>
	      	<%= f.text_field :presentation, :class => 'form-control' %>
	      	<%= f.error_message_on :presentation %>
	    </div>

		<div class="form-group">
	    	<%= f.label :attachment, t(:attachment) %><br />
	      	<%= f.file_field :attachment %>
	      	<%= f.error_message_on :attachment %>
	    </div>
			    
	    <div class="checkbox">
	    	<%= f.label :enabled do %>
	      		<%= f.check_box :enabled %> <%= t(:enabled) %>
	      	<% end %>
	      	<%= f.error_message_on :enabled %>
	    </div>
			
		<div class="right eight columns omega" data-hook="admin_banner_box_form_right">
	    	<% unless f.object.new_record? %>
	      		<div data-hook="thumbnail" class="field alpha two columns">
	        	<%= f.label t(:thumbnail) %><br>
	        	<%= link_to image_tag(@banner_box.attachment.url(:mini)), @banner_box.attachment.url(:small) %>
	      		</div>
			<% end %>
		</div>
	
		<div data-hook="admin_banner_box_form_additional_fields"></div>
	</div>
</div>

app/views/spree/admin/banner_boxes/_tabs.html.erb
<div id="banner_boxes_menu_container" class="row">
	<div class="col-md-9 col-sm-9">
		<% %w[logos compra narrow lateral landing marcas].each do |cat| %>
			<%= link_to cat, admin_banner_boxes_url(category:cat), class:(params[:category] == cat ? 'btn btn-primary active' : 'btn btn-primary') %>
		<% end %>
	</div>

	<div class="col-md-3 col-sm-3">
		<%= form_for admin_banner_boxes_path, :method => 'get' do %>
			<%= hidden_field_tag :category, params[:category] %>
			<div class="field_container">
				<%= label_tag :enabled, "Show only enabled?" %><%= check_box_tag :enabled, '1', params[:enabled] %>
			</div>
		<% end %>
	</div>
</div>

app/views/spree/admin/banner_boxes/edit.html.erb
<%= render :partial => 'spree/admin/shared/banner_box_sub_menu', :locals => { current: :banner_index } %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_banner_boxes_list), admin_banner_boxes_url, :icon => 'icon-arrow-left' %></li>
  <li id="new_banner_box_link">
    <%= button_link_to t(:new_banner_box), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_new_banner_box' } %>
  </li>
<% end %>

<div id="new_banner_box">
	<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @banner_box } %>

	<%= form_for [:admin, @banner_box], :method => :put, :html => { :multipart => true } do |f| %>
	  <fieldset class="no-border-top">
	    <%= render :partial => 'form', :locals => { :f => f } %>
	    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
	  </fieldset>
	<% end %>
</div>

app/views/spree/admin/banner_boxes/index.html.erb
<% content_for :page_title do %>
	<%= t(:listing_banner_boxes) %>
<% end %>

<% content_for :page_actions do %>
	<%= button_link_to t(:new_banner_box), new_object_url, { :remote => true, :id => 'admin_new_banner_box', class: "btn-success", icon: 'add' } %>
<% end %>

<%= render :partial => 'spree/admin/shared/banner_box_sub_menu', :locals => { current: :banner_index } %>

<div id="new_banner_box" data-hook></div>

<%= render :partial => 'tabs' if false %>

<% if @collection.any? %>
<div class="table-responsive">
	<table class="table table-bordered index sortable" id="listing_banner_boxes" data-sortable-link="<%= update_positions_admin_banner_boxes_url() %>">
		<thead>
			<tr data-hook="admin_products_index_headers">
				<th colspan="2"><%= t(:thumbnail) %></th>
				<th><%= t(:category) %></th>
				<th><%= t(:enabled) %></th>
				<th><%= t(:url) %></th>
				<th data-hook="admin_products_index_header_actions" class="actions"></th>
			</tr>
		</thead>
		<tbody>
			<% @collection.each do |banner_box| %>
			<tr id="<%= spree_dom_id banner_box %>" data-hook="admin_banner_boxes_index_row" class="<%= cycle('odd', 'even') %>">
				<td class="move-handle text-center"><span class="icon icon-move handle"></span></td>
				<td class="text-center"><%= image_tag(banner_box.attachment(:mini)) %></td>
				<td class="text-center"><%= banner_box.category rescue '' %></td>
				<td class="text-center"><%= banner_box.enabled rescue '' %></td>
				<td class="text-center"><%= truncate(banner_box.url, :length => 50) %></td>
				<td class="text-center actions" data-hook="admin_products_index_row_actions">
					<%= link_to_edit banner_box, :no_text => true, :class => 'edit' %>
					&nbsp;
					<%= link_to_with_icon 'icon icon-file', '', clone_admin_banner_box_url(banner_box), :no_text => true, :class => 'clone btn btn-info btn-sm' %>
		            &nbsp;
					<%= link_to_delete banner_box, :no_text => true %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<% else %>
<div class="no-objects-found">
	<%= t(:no_results) %>
</div>
<% end %>

<%= paginate @collection %>

<script type="text/javascript">
$("#banner_boxes_menu_container input").on("change", function(e){
	$("#banner_boxes_menu_container form").submit();
});
</script>

app/views/spree/admin/banner_boxes/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @banner_box } %>

<%= form_for [:admin, @banner_box], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_banner_box">
    <legend align="center"><%= t(:new_banner_box) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/banner_boxes/new.js.erb
$("#new_banner_box").html('<%= escape_javascript(render :template => "spree/admin/banner_boxes/new", :formats => [:html], :handlers => [:erb]) %>');
$("#admin_new_banner_box").parent().hide();