config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resources :banner_boxes do
      collection do
        post :update_positions
      end
      member do
        get :clone
      end
    end
    resource :banner_box_settings
  end
end

app/controllers/spree/admin/banner_box_settings_controller.rb
module Spree
  module Admin
    class BannerBoxSettingsController < Spree::Admin::BaseController
      
      def show
        redirect_to( :action => :edit )
      end

      def edit
        @styles = ActiveSupport::JSON.decode(Spree::Config[:banner_styles])
      end

      def update
        update_styles(params)

        Spree::Config.set(params[:preferences])
        update_paperclip_settings

        respond_to do |format|
          format.html {
            flash[:notice] = t(:banner_settings_updated)
            redirect_to edit_admin_banner_box_settings_path
          }
        end
      end

      private

      def update_styles(params)
        params[:new_banner_styles].each do |index, style|
          params[:banner_styles][style[:name]] = style[:value] unless style[:value].empty?
        end if params[:new_banner_styles].present?

        styles = params[:banner_styles]

        Spree::Config[:banner_styles] = ActiveSupport::JSON.encode(styles) unless styles.nil?
      end

      def update_paperclip_settings
        Spree::BannerBox.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:banner_styles]).symbolize_keys!
        # Spree::BannerBox.attachment_definitions[:attachment][:path] = Spree::Config[:banner_path]
        # Spree::BannerBox.attachment_definitions[:attachment][:default_url] = Spree::Config[:banner_default_url]
        # Spree::BannerBox.attachment_definitions[:attachment][:default_style] = Spree::Config[:banner_default_style]
      end
    end
  end
end

app/views/spree/admin/banner_box_settings/edit.html.erb
<% content_for :page_title do %>
  <%= t(:banner_box_settings) %>
<% end %>

<%= render :partial => 'spree/admin/shared/banner_box_sub_menu', :locals => { current: :banner_config } %>

<%= form_tag admin_banner_box_settings_path, :method => :put, :id => 'form_admin_banner_box_settings' do %>

	<fieldset class="no-border-top">

		<div class="field">
  		<div class="warning note"><%= t(:banner_box_settings_warning) %></div>
		</div>

    <br>

    <div class="col-md-6 col-sm-6">
  		<div data-hook="attachment_path" class="form-group">
    		<%= label_tag 'preferences[attachment_path]', t(:banner_path) %>
    		<%= preference_field_tag 'preferences[banner_path]', Spree::Config[:banner_path], :type => :string %>
  		</div>

  		<div data-hook="attachment_default_url" class="form-group">
    		<%= label_tag 'preferences[attachment_default_url]', t(:banner_default_url) %>
    		<%= preference_field_tag 'preferences[banner_default_url]', Spree::Config[:banner_default_url], :type => :string %>
  		</div>
    </div>

    <div class="col-md-6 col-sm-6" data-hook="admin_page_form_right">
  		<div data-hook="attachment_url" class="form-group">
  			<%= label_tag 'preferences[attachment_url]', t(:banner_url) %>
  			<%= preference_field_tag 'preferences[banner_url]', Spree::Config[:banner_url], :type => :string %>
  		</div>

			<div data-hook="attachment_default_style" class="form-group">
  			<%= label_tag 'preferences[attachment_default_style]', t(:banner_default_style) %>
  			<%= collection_select 'preferences', 'banner_default_style', @styles, :first, :first, {:selected => Spree::Config[:banner_default_style] }, :class => 'select2 fullwidth' %>
  		</div>
    </div>

  </fieldset>

  <fieldset class="no-border-bottom no-border-bottom" id="attachment_styles" data-hook="banner_styles">
    <legend align="center"><%= t(:banner_styles) %></legend>

		<div id="banner_styles_list" class="row">
  		<% @styles.each_with_index do |(style_name, style_value), index| %>
      		<div class="form-group col-md-3 col-sm-3">
        		<%= label_tag "banner_styles[#{style_name}]", style_name %>
        		<a href='#' alt="<%= t(:destroy)%>" title="<%= t(:destroy)%>" class='destroy_banner_style with-tip'><i class='icon icon-trash' style="font-size: 11px; margin-top: 3px;"></i></a>
        		<%= text_field_tag "banner_styles[#{style_name}]", style_value, :class => 'form-control' %>
      		</div>
  		<% end %>
		</div>

		<div class="row">
    	<div id="new-banner-styles" class="col-md-12 col-sm-12"></div>
    </div>

		<div class="row">
			<div class="col-md-3 col-sm-3">
  			<%= link_to_with_icon 'icon-plus', t(:add_new_banner_style), '#', :class => 'add_new_banner_style btn btn-primary' %>
			</div>
		</div>
  </fieldset>

	<div class="form-buttons filter-actions actions" data-hook="buttons">
    <%= button t(:update), 'icon-refresh' %>
	</div>

<% end %>